---
title: "Final Project"
author: "Hirsch-Santagata, Pulliam"
format: html
editor: visual
---
#Loading packages
```{r}
library(tidyverse) # for data wrangling and plotting
library(car) # for Anova function
library(lme4)
library(broom) # for model residuals extraction
library(emmeans) # for model mean extraction
library(multcomp) # for pairwise comparison letter display
library(readxl) # for reading excel doc
library(janitor)
library(lmerTest)
library(dplyr)
```


#Bringing in Data 
```{r}
pulliam_proj <- read_excel("data/project_raw_data.xlsx")

pulliam_proj
```

#EDA tables
```{r}
summary(pulliam_proj)

glimpse(pulliam_proj)
```

#Wrangling
```{r}
pulliam_proj_clean <- clean_names(pulliam_proj)

pulliam_proj_w <- pulliam_proj_clean %>%
  mutate(rep = factor(rep),
         date = factor(date),
         day = factor(day),
         trt = factor(trt),
         plot = factor(plot)
         )# %>%
 # mutate(trtname = paste0(,"+",))


#interested in mean effects so we changed variables to be viewed as factors 

pulliam_proj_w
```

#sumamry 
```{r}
summary(pulliam_proj_w)
```


# EDA Plots
```{r fig.width=14, fig.height=6}
#sampling_dates <- c("Day 0", "Day 5", "Day 7", "Day 14", "Day 28", "Day 42", "Day 56", "Day 70","Day 93", "Day 119", "Day 4inc", "Day 14inc", "Day 6pk", "Day 14pk", "Day 30pk", "Day 47pk","Day 63pk", "Day 78pk", "Day 86pk")

#pulliam_proj_w$day <- factor(pulliam_proj_w$day, levels = original_day_order)

ggplot(pulliam_proj_w, aes(x = trt, 
                    y = mg_kg_tin,
                    color = trt)) +
  geom_boxplot() +
  geom_jitter() +
  theme(legend.position = "right") +
  
  
  facet_wrap(~ day)

# or could use facet_grid( ~ day) for one big graphic

ggplot(pulliam_proj_w, aes(x = trt, 
                    y = mg_kg_tin,
                    color = trt)) +
  geom_boxplot() +
  geom_jitter() +
  theme(legend.position = "right") +
  
  
  facet_grid(~ day)


```


#Faceting longer by day? (or sampling date)
```{r}
#pulliam_wide <- pulliam_proj_w %>%
  #unite("day_trt", day, trt, sep = "_") %>%
 # pivot_wider(names_from = day_trt, values_from = mg_kg_tin,
           #   values_fill = 0) ## this last bit is to ake NA to 0 

#pulliam_wide


```


# Statistical Model
```{r}
options(contrasts = c("contr.sum", "contr.poly"))

pulliam_proj_mod <- lmer(mg_kg_tin ~ trt +
                       (1|rep),
                     data = pulliam_proj_w
                       )

pulliam_proj_mod
```

#Anova
```{r}
Anova(pulliam_proj_mod, type=3)
```

#Linear Model Assumptions
## extracting residuals 
```{r}
library(broom.mixed)
pulliam_proj_mix_resid <- augment(pulliam_proj_mod) %>%
  mutate(.studresid=rstudent(pulliam_proj_mod))

pulliam_proj_mix_resid
```
#Random effect are iid
```{r}
randeff_rep <- ranef(pulliam_proj_mod) [[1]]

randeff_rep
```

##QQPLot
```{r}
ggplot(randeff_rep, aes(sample=`(Intercept)`))+
  stat_qq(  shape = 21,
            fill = "purple", 
            size = 3,
            alpha = .7
  )+
  stat_qq_line()+
  labs(x = "Theoretical quantile",
       y = "Sample quantile")+
  theme_bw()
```


##within group errors are iid
```{r}
ggplot(pulliam_proj_mix_resid, aes(x=.fitted, y=.studresid))+
  geom_hline(yintercept = 0, color="red")+
  geom_point(shape = 21,
             fill = "purple", 
             size = 3,
             alpha = .7)+
  geom_smooth()+
  geom_hline(yintercept = c(-3,3), color = "red")+
  theme_bw()
```

```{r}
ggplot(pulliam_proj_mix_resid, aes(sample=.studresid))+
  stat_qq(  shape = 21,
            fill = "purple", 
            size = 3,
            alpha = .7
  )+
  stat_qq_line()+
  labs(x = "Theoretical quantile",
       y = "Sample quantile")+
  theme_bw()
```


```{r}
ggplot(pulliam_proj_mix_resid, aes(x=.studresid))+
  geom_density(color = "black",
               fill = "purple",
               alpha = .7)+
  scale_x_continuous(breaks = c(-3,0,3), limits = c(-3,3))+
  theme_bw()
```
#Model Means

```{r}
pulliam_proj_means_all <- emmeans(pulliam_proj_mod, ~trt:day)

pulliam_proj_means_all
```




























