<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Hirsch-Santagata, Pulliam">

<title>Final Project</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="FinalProject_files/libs/clipboard/clipboard.min.js"></script>
<script src="FinalProject_files/libs/quarto-html/quarto.js"></script>
<script src="FinalProject_files/libs/quarto-html/popper.min.js"></script>
<script src="FinalProject_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="FinalProject_files/libs/quarto-html/anchor.min.js"></script>
<link href="FinalProject_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="FinalProject_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="FinalProject_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="FinalProject_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="FinalProject_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Final Project</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Hirsch-Santagata, Pulliam </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse) <span class="co"># for data wrangling and plotting</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car) <span class="co"># for Anova function</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData

Attaching package: 'car'

The following object is masked from 'package:dplyr':

    recode

The following object is masked from 'package:purrr':

    some</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: Matrix

Attaching package: 'Matrix'

The following objects are masked from 'package:tidyr':

    expand, pack, unpack</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom) <span class="co"># for model residuals extraction</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans) <span class="co"># for model mean extraction</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Welcome to emmeans.
Caution: You lose important information if you filter this package's results.
See '? untidy'</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(multcomp) <span class="co"># for pairwise comparison letter display</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: mvtnorm
Loading required package: survival
Loading required package: TH.data
Loading required package: MASS

Attaching package: 'MASS'

The following object is masked from 'package:dplyr':

    select


Attaching package: 'TH.data'

The following object is masked from 'package:MASS':

    geyser</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl) <span class="co"># for reading excel doc</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'janitor'

The following objects are masked from 'package:stats':

    chisq.test, fisher.test</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmerTest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'lmerTest'

The following object is masked from 'package:lme4':

    lmer

The following object is masked from 'package:stats':

    step</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Organic growers use a wide variety of fertilizers and materials to supply nutrients based on crop requirements. In the southeastern US, poultry litter (PL) is widely accessible and available for growers as a nutrient source, but growers must abide by the National Organic Program’s (NOP) “90-120-Day Rule”. The NOP specifies that manures must be applied 90 days before the harvest of food crops and 120 days before the harvest of food crops that have contact with the soil. The requirements of the 90-120-Day rule make it difficult to synchronize the mineralization of manures with crop demand, especially in terms of nitrogen. Applying the poultry litter to the cover crop, rather than at cash crop planting, allows the cover crop to uptake nutrients (nitrogen) from poultry litter with the potential to increase biomass and weed suppression, while reducing the risk of food-borne pathogens and the potential for nitrogen loss.</p>
<p>In conventional vegetable production, nitrogen availability in inorganic fertilizer is both plentiful and readily available for plant uptake. However, in organic production, farmers have of choice of costly certified organic fertilizers or other organic materials like compost, manures, and cover crops. Despite their accessibility and low costs, organic growers are hesitant to use manures such as poultry litter due to the risk of food-borne pathogens and regulations for using raw manure. The NOP states that manures must be applied ninety days before harvest for crops not in contact with the soil and 120 days before harvest for crops in contact with the soil. By applying broiler litter to cover crops, these plants can uptake the nutrients released from poultry litter, and as the cover crops decompose, release those nutrients for the use by cash crops without the risk of contamination by pathogens. Currently, the papers published in this field are all similar in the way of poultry application impacts on cover crops are studied and reported. Most of these studies look at biomass immediately before the termination of cover crops and only begin to measure soil inorganic nitrogen after cover crop termination. The study proposed here will vary from previous studies in testing the effects of poultry litter application on biomass and soil inorganic nitrogen from the seeding of the cover crop all the way through final harvest of the cash crop, instead of after the cover crop is terminated. Additionally, the study will examine how the quality of the cover crop affects subsequent nutrient availability and rate of release. The available literature also tends to focus on above ground biomass only and does not examine the effects on root biomass. The proposed project will also examine the role that root biomass and root nutrient content play in nutrient release and mineralization. In measuring these additional parameters and taking a more in-depth approach to previously conducted research, a better understanding of the uptake, release, and availability of nutrients can be formed.</p>
<p>The objective of this study is to determine the effects of poultry litter application to cover crops on cover crop biomass, weed suppression, soil inorganic nitrogen, and nutrient availability for the subsequent cash crop. To analyze the cover crop uptake of nutrients from poultry litter and subsequent release of nutrients from cover crop mineralization, the previously mentioned parameters will be measured before application of poultry litter then on days 4, 7, 14, and every two weeks until cover crop termination. The same sampling approach will be used for kale cycle from transplant to final harvest. Additionally, kale plant heights, chlorophyll measurement, and yield will be collected and analyzed.</p>
<p>Using the collected data through rigorous sampling dates, the proposed project could provide an in-depth understanding of nutrient uptake and release from cover crops and its impact on the following organic vegetable system.</p>
</section>
<section id="hypothesis-and-objectives" class="level1">
<h1>Hypothesis and Objectives</h1>
<section id="hypothesis" class="level3">
<h3 class="anchored" data-anchor-id="hypothesis">Hypothesis</h3>
<p>Poultry litter application will increase cover crop biomass, weed suppression, soil nitrogen concentrations, and nutrient availability for successive organic vegetable systems.</p>
</section>
<section id="objectives" class="level3">
<h3 class="anchored" data-anchor-id="objectives">Objectives</h3>
<ol type="a">
<li>Determine the effect of poultry litter application to cover crops on biomass, weed suppression, soil nitrogen concentrations, and nutrient availability.</li>
<li>Determine the effect of poultry litter application on subsequent nitrogen availability released from cover crop.</li>
<li>Determine the effect of poultry litter applications on cover crop quality as defined by cover crop composition of lignin, cellulose, and C:N ratio.</li>
</ol>
</section>
</section>
<section id="material-and-methods" class="level1">
<h1>Material and Methods</h1>
<p>The two-year field study will take place on organic certified land at the University of Georgia’s Durham Horticulture farm in Watkinsville, GA. The farm has soils classified as a Cecil sandy loam by the United States Department of Agriculture (USDA). The plot will be 10 x 20 ft in a randomized complete block design. Four treatments of poultry litter will be applied at 0 (control treatment),1,2, and 4 tons per acre with four replication per treatment making a total of sixteen blocks. Organic oats will be seeded at a rate of 110 lbs per acre. At the end of the cover crop cycle, the oats will be flail-mowed and incorporated into the soil. Three weeks after incorporation of oats, the cash crop, kale (Brassica oleracea ‘Winterbor’) will be planted with 12” spacing in-row and 24” spacing between row with four rows per treatment (each treatment having fourty-eight plants total). Kale will be the subsequent cash crop as it is a staple crop for organic growers in the southeast and will be able to clearly reveal any differences in nitrogen accumulations between treatments when measuring various parameters.</p>
<p>To determine the effect of poultry litter on biomass of the cover crop, samples will be taken four times through the cover crop cycle using a 1 x 1 ft quadrat to harvest biomass at soil level, which will be dried at 65°C. Once dried, samples will be weighed, and their dry weight will be recorded. Additionally, light interception of the cover crops will be measured using the LP-80 (METER Group). Soil samples will be taken prior to poultry litter application, at 4,7, and 14 days after application then every two weeks until cover crop termination to determine soil inorganic nitrogen. The soil samples will be extracted in 1M KCl, then amounts of soil inorganic nitrogen will be calculated using a Timberline Instruments Ammonia Analyzer. Soil samples taken prior to poultry litter application will be analyzed for routine nutrient analysis, total nitrogen and carbon, and organic matter. At cover crop termination, biomass sample will be analyzed for total nitrogen, total carbon, carbohydrates, cellulose, and lignin using the NIRS DS5200 (Foss). Mineralization of these cover crops will be determined using the UGA Cover Crop Nitrogen Availability Calculator. Kale will be measured for nutrient uptake through soil samples taken at planting, and at 4,7, and 14 days after planting then every two weeks until final harvest. Leaf nitrate concentrations will be determined by harvesting two mature leaves and two new leaves per treatment block. Nitrate concentrations will be quantified using the same method used to determine soil nitrogen concentrations. To determine nitrogen availability for subsequent vegetable system, kale will be harvested four times throughout the study to and measured for nitrate, quality, dry weight, and overall yield.</p>
</section>
<section id="study-design" class="level1">
<h1>Study design</h1>
<p>This study design is a randomized complete block design. There are 4 poultry litter application treatments with 4 replications randomized in 4 blocks (16 plots total). Randomization was conducted by take the 16 plot IDs and putting them into a web-generated randomized plot.</p>
<section id="statistical-analysis" class="level2">
<h2 class="anchored" data-anchor-id="statistical-analysis">Statistical analysis</h2>
<p>Data will be analyzed using a type 3, analysis of variance (ANOVA) model in the program R (R Core Team). The independent (treatment) variable in the proposed will be the rate of poultry litter application, while dependent variables will include soil nitrogen, biomass, plant nitrate, plant height, and chlorophyll. When ANOVA indicated significance, Tukey’s HSD was used to separate means at p &lt; 0.05. The models were run using the lmer function from the stats package in R. We checked linear model assumptions by extracting residuals and plotting on a QQ plot to look for linearity between our sample quantile and the theoretical. We checked for within group errors by plotting studentized residuals versus fitted ones, looking for outliers above 3 or below -3, while looking for possible patterns - where we did notice a fan shaped structure within our data. Which wasn’t something we had encountered or new how to fit our model to compensate for. Then with out studentized residuals we fitted to a QQ plot again to look for linearity between our sample quantile and the theoretical, which can back okay, with a linearity to the data without too much cause for concern. Finally we used geom_density function to look at the studentized residuals and how they lay between points of 3 and -3, to which we saw the majority of points fell near 0, with a clear bell-shaped pattern pattern. Overall when checking for normality or model seems to pass - besides the fan shape we noticed but that is outside the bounds of our course. For our work in R we used the following packages: tidyverse (for wrangling and plotting), car (for the Anova function), lme4 (to run our statistical model), broom (for model residual extractions), emmeans (for model means extraction), multicomp (for pairwise letters comparisons), readxl (to read and bring in our excel data), janitor (to wrangle and clean our excel data we import), LmerTest (to display the p-values next to the mdoel once run), and dyplr (for overall functionality)</p>
</section>
<section id="bringing-in-data" class="level2">
<h2 class="anchored" data-anchor-id="bringing-in-data">Bringing in Data</h2>
<p>Here we are bringing in our data set with the read_excel funtion through the readxl package which we configured and edited to run in R</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>pulliam_proj <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"../data/project_raw_data.xlsx"</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>pulliam_proj</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 304 × 13
   Date                  Day  Plot   Trt   Rep `NH3 Conc.` `NO3 + NH3 Conc.`
   &lt;dttm&gt;              &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;       &lt;dbl&gt;             &lt;dbl&gt;
 1 2023-10-04 00:00:00     0   101     1     1       0.416              4.12
 2 2023-10-04 00:00:00     0   201     1     2       0.846              6.52
 3 2023-10-04 00:00:00     0   301     1     3       0.529              4.59
 4 2023-10-04 00:00:00     0   401     1     4       0.416              3.16
 5 2023-10-04 00:00:00     0   102     2     1       0.524              5.00
 6 2023-10-04 00:00:00     0   202     2     2       0.672              4.58
 7 2023-10-04 00:00:00     0   302     2     3       0.435              3.54
 8 2023-10-04 00:00:00     0   402     2     4       0.570              6.34
 9 2023-10-04 00:00:00     0   103     3     1       0.347              3.98
10 2023-10-04 00:00:00     0   203     3     2       0.492              4.64
# ℹ 294 more rows
# ℹ 6 more variables: `NO3 Conc.` &lt;dbl&gt;, `L KCl` &lt;dbl&gt;,
#   `kg air dry soil` &lt;dbl&gt;, `mg/kg NH3` &lt;dbl&gt;, `mg/kg TIN` &lt;dbl&gt;,
#   `mg/kg NO3` &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
</section>
<section id="eda-tables" class="level1">
<h1>EDA tables</h1>
<p>Here we are printing the summary and glimpsing at our data to get an understanding of how are variables are being interpreted and looking at the general stats so far with the raw data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pulliam_proj)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Date                             Day             Plot      
 Min.   :2023-10-04 00:00:00.00   Min.   :  0.0   Min.   :101.0  
 1st Qu.:2023-11-01 00:00:00.00   1st Qu.: 28.0   1st Qu.:176.8  
 Median :2024-01-31 00:00:00.00   Median :119.0   Median :252.5  
 Mean   :2024-01-16 21:28:25.25   Mean   :104.4   Mean   :252.5  
 3rd Qu.:2024-03-21 00:00:00.00   3rd Qu.:168.0   3rd Qu.:328.2  
 Max.   :2024-05-16 00:00:00.00   Max.   :224.0   Max.   :404.0  
      Trt            Rep         NH3 Conc.      NO3 + NH3 Conc.  
 Min.   :1.00   Min.   :1.00   Min.   :0.2137   Min.   : 0.3148  
 1st Qu.:1.75   1st Qu.:1.75   1st Qu.:0.3416   1st Qu.: 0.7823  
 Median :2.50   Median :2.50   Median :0.4258   Median : 1.5517  
 Mean   :2.50   Mean   :2.50   Mean   :0.5093   Mean   : 2.4290  
 3rd Qu.:3.25   3rd Qu.:3.25   3rd Qu.:0.5370   3rd Qu.: 3.5836  
 Max.   :4.00   Max.   :4.00   Max.   :3.8688   Max.   :12.3738  
   NO3 Conc.           L KCl      kg air dry soil   mg/kg NH3     
 Min.   : 0.0448   Min.   :0.04   Min.   :0.005   Min.   : 1.710  
 1st Qu.: 0.3946   1st Qu.:0.04   1st Qu.:0.005   1st Qu.: 2.733  
 Median : 1.0090   Median :0.04   Median :0.005   Median : 3.406  
 Mean   : 1.9197   Mean   :0.04   Mean   :0.005   Mean   : 4.074  
 3rd Qu.: 2.9601   3rd Qu.:0.04   3rd Qu.:0.005   3rd Qu.: 4.296  
 Max.   :11.8507   Max.   :0.04   Max.   :0.005   Max.   :30.950  
   mg/kg TIN        mg/kg NO3      
 Min.   : 2.518   Min.   : 0.3584  
 1st Qu.: 6.258   1st Qu.: 3.1566  
 Median :12.414   Median : 8.0716  
 Mean   :19.432   Mean   :15.3579  
 3rd Qu.:28.669   3rd Qu.:23.6806  
 Max.   :98.990   Max.   :94.8056  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(pulliam_proj)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 304
Columns: 13
$ Date              &lt;dttm&gt; 2023-10-04, 2023-10-04, 2023-10-04, 2023-10-04, 202…
$ Day               &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5…
$ Plot              &lt;dbl&gt; 101, 201, 301, 401, 102, 202, 302, 402, 103, 203, 30…
$ Trt               &lt;dbl&gt; 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 1, 1…
$ Rep               &lt;dbl&gt; 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2…
$ `NH3 Conc.`       &lt;dbl&gt; 0.4157, 0.8455, 0.5286, 0.4156, 0.5237, 0.6722, 0.43…
$ `NO3 + NH3 Conc.` &lt;dbl&gt; 4.1173, 6.5245, 4.5891, 3.1610, 4.9997, 4.5803, 3.53…
$ `NO3 Conc.`       &lt;dbl&gt; 3.7016, 5.6790, 4.0604, 2.7454, 4.4761, 3.9081, 3.10…
$ `L KCl`           &lt;dbl&gt; 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04…
$ `kg air dry soil` &lt;dbl&gt; 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.005, 0.0…
$ `mg/kg NH3`       &lt;dbl&gt; 3.3256, 6.7640, 4.2288, 3.3248, 4.1896, 5.3776, 3.48…
$ `mg/kg TIN`       &lt;dbl&gt; 32.9384, 52.1960, 36.7128, 25.2880, 39.9976, 36.6424…
$ `mg/kg NO3`       &lt;dbl&gt; 29.6128, 45.4320, 32.4832, 21.9632, 35.8088, 31.2648…</code></pre>
</div>
</div>
<section id="wrangling" class="level2">
<h2 class="anchored" data-anchor-id="wrangling">Wrangling</h2>
<p>Here we are doing some light wrangling of the data, cleaning names to make coding easier down the line and primarily changing variables form being looked at as numerical to being viewed as factors, as they play important role in how are data is interpreted</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>pulliam_proj_clean <span class="ot">&lt;-</span> <span class="fu">clean_names</span>(pulliam_proj)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>pulliam_proj_w <span class="ot">&lt;-</span> pulliam_proj_clean <span class="sc">%&gt;%</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">rep =</span> <span class="fu">factor</span>(rep),</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">date =</span> <span class="fu">factor</span>(date),</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">day =</span> <span class="fu">factor</span>(day),</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">trt =</span> <span class="fu">factor</span>(trt),</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">plot =</span> <span class="fu">factor</span>(plot)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>         )<span class="co"># %&gt;%</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a> <span class="co"># mutate(trtname = paste0(,"+",))</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a><span class="co">#interested in mean effects so we changed variables to be viewed as factors </span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>pulliam_proj_w</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 304 × 13
   date       day   plot  trt   rep   nh3_conc no3_nh3_conc no3_conc l_k_cl
   &lt;fct&gt;      &lt;fct&gt; &lt;fct&gt; &lt;fct&gt; &lt;fct&gt;    &lt;dbl&gt;        &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;
 1 2023-10-04 0     101   1     1        0.416         4.12     3.70   0.04
 2 2023-10-04 0     201   1     2        0.846         6.52     5.68   0.04
 3 2023-10-04 0     301   1     3        0.529         4.59     4.06   0.04
 4 2023-10-04 0     401   1     4        0.416         3.16     2.75   0.04
 5 2023-10-04 0     102   2     1        0.524         5.00     4.48   0.04
 6 2023-10-04 0     202   2     2        0.672         4.58     3.91   0.04
 7 2023-10-04 0     302   2     3        0.435         3.54     3.10   0.04
 8 2023-10-04 0     402   2     4        0.570         6.34     5.77   0.04
 9 2023-10-04 0     103   3     1        0.347         3.98     3.63   0.04
10 2023-10-04 0     203   3     2        0.492         4.64     4.15   0.04
# ℹ 294 more rows
# ℹ 4 more variables: kg_air_dry_soil &lt;dbl&gt;, mg_kg_nh3 &lt;dbl&gt;, mg_kg_tin &lt;dbl&gt;,
#   mg_kg_no3 &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
<section id="sumamry" class="level2">
<h2 class="anchored" data-anchor-id="sumamry">Sumamry</h2>
<p>Here we are looking at the summary again to ensure no mistakes were made</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(pulliam_proj_w)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         date          day           plot     trt    rep       nh3_conc     
 2023-10-04: 16   0      : 16   101    : 19   1:76   1:76   Min.   :0.2137  
 2023-10-10: 16   5      : 16   102    : 19   2:76   2:76   1st Qu.:0.3416  
 2023-10-12: 16   7      : 16   103    : 19   3:76   3:76   Median :0.4258  
 2023-10-19: 16   14     : 16   104    : 19   4:76   4:76   Mean   :0.5093  
 2023-11-01: 16   28     : 16   201    : 19                 3rd Qu.:0.5370  
 2023-11-15: 16   42     : 16   202    : 19                 Max.   :3.8688  
 (Other)   :208   (Other):208   (Other):190                                 
  no3_nh3_conc        no3_conc           l_k_cl     kg_air_dry_soil
 Min.   : 0.3148   Min.   : 0.0448   Min.   :0.04   Min.   :0.005  
 1st Qu.: 0.7823   1st Qu.: 0.3946   1st Qu.:0.04   1st Qu.:0.005  
 Median : 1.5517   Median : 1.0090   Median :0.04   Median :0.005  
 Mean   : 2.4290   Mean   : 1.9197   Mean   :0.04   Mean   :0.005  
 3rd Qu.: 3.5836   3rd Qu.: 2.9601   3rd Qu.:0.04   3rd Qu.:0.005  
 Max.   :12.3738   Max.   :11.8507   Max.   :0.04   Max.   :0.005  
                                                                   
   mg_kg_nh3        mg_kg_tin        mg_kg_no3      
 Min.   : 1.710   Min.   : 2.518   Min.   : 0.3584  
 1st Qu.: 2.733   1st Qu.: 6.258   1st Qu.: 3.1566  
 Median : 3.406   Median :12.414   Median : 8.0716  
 Mean   : 4.074   Mean   :19.432   Mean   :15.3579  
 3rd Qu.: 4.296   3rd Qu.:28.669   3rd Qu.:23.6806  
 Max.   :30.950   Max.   :98.990   Max.   :94.8056  
                                                    </code></pre>
</div>
</div>
</section>
</section>
<section id="eda-plots" class="level1">
<h1>EDA Plots</h1>
<p>Here we are trying to layout the data and look at possible presentations, sectioning out our main variables of trt and day to get an understanding on how it will impact our dependednt variable of total inorganic nitrogen (mg_kg_tin)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">#sampling_dates &lt;- c("Day 0", "Day 5", "Day 7", "Day 14", "Day 28", "Day 42", "Day 56", "Day 70","Day 93", "Day 119", "Day 4inc", "Day 14inc", "Day 6pk", "Day 14pk", "Day 30pk", "Day 47pk","Day 63pk", "Day 78pk", "Day 86pk")</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="co">#pulliam_proj_w$day &lt;- factor(pulliam_proj_w$day, levels = original_day_order)</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pulliam_proj_w, <span class="fu">aes</span>(<span class="at">x =</span> trt, </span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">y =</span> mg_kg_tin,</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>                    <span class="at">color =</span> trt)) <span class="sc">+</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>() <span class="sc">+</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"right"</span>) <span class="sc">+</span></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> day)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProject_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="1344"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># or could use facet_grid( ~ day) for one big graphic</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pulliam_proj_w, <span class="fu">aes</span>(<span class="at">x =</span> trt, </span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">y =</span> mg_kg_tin,</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>                    <span class="at">color =</span> trt)) <span class="sc">+</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>() <span class="sc">+</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"right"</span>) <span class="sc">+</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="sc">~</span> day)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProject_files/figure-html/unnamed-chunk-6-2.png" class="img-fluid figure-img" width="1344"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="statistical-model" class="level1">
<h1>Statistical Model</h1>
<p>Here we are creating our statistical model through the lme4 package using the lmer function, where we assume rep as randome and are attempting to exlain mg_kg_tin through the varaibles of trt and day</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">contrasts =</span> <span class="fu">c</span>(<span class="st">"contr.sum"</span>, <span class="st">"contr.poly"</span>))</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>pulliam_proj_mod <span class="ot">&lt;-</span> <span class="fu">lmer</span>(mg_kg_tin <span class="sc">~</span> trt <span class="sc">*</span> day <span class="sc">+</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>                       (<span class="dv">1</span><span class="sc">|</span>rep),</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> pulliam_proj_w</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>                       )</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>pulliam_proj_mod</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerModLmerTest']
Formula: mg_kg_tin ~ trt * day + (1 | rep)
   Data: pulliam_proj_w
REML criterion at convergence: 1724.003
Random effects:
 Groups   Name        Std.Dev.
 rep      (Intercept) 1.565   
 Residual             7.052   
Number of obs: 304, groups:  rep, 4
Fixed Effects:
(Intercept)         trt1         trt2         trt3         day1         day2  
   19.43212     -5.18481     -1.21491     -0.01724     18.14533     30.41583  
       day3         day4         day5         day6         day7         day8  
   13.52418     17.73853     16.57798     14.91913     -4.42217    -11.30592  
       day9        day10        day11        day12        day13        day14  
  -10.26507    -13.49252     -9.37802    -15.13347     -2.31057      4.19053  
      day15        day16        day17        day18    trt1:day1    trt2:day1  
    4.95428    -12.22692    -14.07657    -13.62122      4.39116      2.54786  
  trt3:day1    trt1:day2    trt2:day2    trt3:day2    trt1:day3    trt2:day3  
   -2.05161    -10.06954      3.04936     -0.08831      2.14891     -7.73179  
  trt3:day3    trt1:day4    trt2:day4    trt3:day4    trt1:day5    trt2:day5  
   -2.14626     -6.23904      1.24566     -1.89541    -13.87609     -0.33699  
  trt3:day5    trt1:day6    trt2:day6    trt3:day6    trt1:day7    trt2:day7  
   -0.72946    -11.99964    -14.05754      3.55679     -0.30134     -2.92264  
  trt3:day7    trt1:day8    trt2:day8    trt3:day8    trt1:day9    trt2:day9  
   -5.50571      2.88201      0.41191     -0.62236      2.57216     -0.03654  
  trt3:day9   trt1:day10   trt2:day10   trt3:day10   trt1:day11   trt2:day11  
   -0.67841      3.34481      1.73871      0.41224      3.10811     -0.27559  
 trt3:day11   trt1:day12   trt2:day12   trt3:day12   trt1:day13   trt2:day13  
   -1.79206      4.23276      0.92906      1.06459      1.01706      1.82156  
 trt3:day13   trt1:day14   trt2:day14   trt3:day14   trt1:day15   trt2:day15  
    3.28469     -4.79404      4.18686      7.83739      3.57761      6.10731  
 trt3:day15   trt1:day16   trt2:day16   trt3:day16   trt1:day17   trt2:day17  
   -0.91296      4.09681      0.54171      0.27664      4.98166      1.20336  
 trt3:day17   trt1:day18   trt2:day18   trt3:day18  
   -0.07651      4.96431      0.73261      0.35234  </code></pre>
</div>
</div>
</section>
<section id="anova" class="level1">
<h1>Anova</h1>
<p>Here we are running a type 3 ANOVA model to look at significance</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">Anova</span>(pulliam_proj_mod, <span class="at">type=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table (Type III Wald chisquare tests)

Response: mg_kg_tin
              Chisq Df Pr(&gt;Chisq)    
(Intercept)  486.79  1  &lt; 2.2e-16 ***
trt          106.27  3  &lt; 2.2e-16 ***
day         1217.57 18  &lt; 2.2e-16 ***
trt:day      205.25 54  &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="linear-model-assumptions" class="level1">
<h1>Linear Model Assumptions</h1>
<section id="extracting-residuals" class="level2">
<h2 class="anchored" data-anchor-id="extracting-residuals">Extracting residuals</h2>
<p>Here we are extracting residuals to begin chekcing normality</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom.mixed)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>pulliam_proj_mix_resid <span class="ot">&lt;-</span> <span class="fu">augment</span>(pulliam_proj_mod) <span class="sc">%&gt;%</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">.studresid=</span><span class="fu">rstudent</span>(pulliam_proj_mod))</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>pulliam_proj_mix_resid</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 304 × 16
   mg_kg_tin trt   day   rep   .fitted  .resid  .hat   .cooksd .fixed   .mu
       &lt;dbl&gt; &lt;fct&gt; &lt;fct&gt; &lt;fct&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
 1      32.9 1     0     1        36.7  -3.81  0.258 0.00179     36.8  36.7
 2      52.2 1     0     2        38.7  13.5   0.258 0.0225      36.8  38.7
 3      36.7 1     0     3        36.2   0.523 0.258 0.0000338   36.8  36.2
 4      25.3 1     0     4        35.5 -10.2   0.258 0.0129      36.8  35.5
 5      40.0 2     0     1        38.9   1.13  0.258 0.000157    38.9  38.9
 6      36.6 2     0     2        40.8  -4.20  0.258 0.00219     38.9  40.8
 7      28.3 2     0     3        38.3 -10.0   0.258 0.0124      38.9  38.3
 8      50.7 2     0     4        37.6  13.1   0.258 0.0213      38.9  37.6
 9      31.8 3     0     1        35.5  -3.67  0.258 0.00167     35.5  35.5
10      37.1 3     0     2        37.4  -0.327 0.258 0.0000133   35.5  37.4
# ℹ 294 more rows
# ℹ 6 more variables: .offset &lt;dbl&gt;, .sqrtXwt &lt;dbl&gt;, .sqrtrwt &lt;dbl&gt;,
#   .weights &lt;dbl&gt;, .wtres &lt;dbl&gt;, .studresid &lt;dbl&gt;</code></pre>
</div>
</div>
</section>
<section id="random-effect-are-iid" class="level2">
<h2 class="anchored" data-anchor-id="random-effect-are-iid">Random Effect are iid</h2>
<p>Here we are looking at radnom effect</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>randeff_rep <span class="ot">&lt;-</span> <span class="fu">ranef</span>(pulliam_proj_mod) [[<span class="dv">1</span>]]</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>randeff_rep</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  (Intercept)
1  -0.0392316
2   1.9354478
3  -0.5937237
4  -1.3024924</code></pre>
</div>
</div>
</section>
<section id="qqplot" class="level2">
<h2 class="anchored" data-anchor-id="qqplot">QQPlot</h2>
<p>Here we create a QQ plot to check the linear model assumptions fo the random effect</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(randeff_rep, <span class="fu">aes</span>(<span class="at">sample=</span><span class="st">`</span><span class="at">(Intercept)</span><span class="st">`</span>))<span class="sc">+</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq</span>(  <span class="at">shape =</span> <span class="dv">21</span>,</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">fill =</span> <span class="st">"purple"</span>, </span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">size =</span> <span class="dv">3</span>,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">alpha =</span> .<span class="dv">7</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  )<span class="sc">+</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>()<span class="sc">+</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Theoretical quantile"</span>,</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Sample quantile"</span>)<span class="sc">+</span></span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProject_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="within-group-errors-are-iid" class="level2">
<h2 class="anchored" data-anchor-id="within-group-errors-are-iid">Within Group Errors are iid</h2>
<p>Here we plot residuals, studentized and fitted to look for outliers and normality issues (if we see a pattern)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pulliam_proj_mix_resid, <span class="fu">aes</span>(<span class="at">x=</span>.fitted, <span class="at">y=</span>.studresid))<span class="sc">+</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">color=</span><span class="st">"red"</span>)<span class="sc">+</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">shape =</span> <span class="dv">21</span>,</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>             <span class="at">fill =</span> <span class="st">"purple"</span>, </span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">size =</span> <span class="dv">3</span>,</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">alpha =</span> .<span class="dv">7</span>)<span class="sc">+</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>()<span class="sc">+</span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>,<span class="dv">3</span>), <span class="at">color =</span> <span class="st">"red"</span>)<span class="sc">+</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using method = 'loess' and formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProject_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="qqplot-1" class="level2">
<h2 class="anchored" data-anchor-id="qqplot-1">QQplot</h2>
<p>Here we check linear normality using the studentized residuals, keeping an eye out for unique patterns</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pulliam_proj_mix_resid, <span class="fu">aes</span>(<span class="at">sample=</span>.studresid))<span class="sc">+</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq</span>(  <span class="at">shape =</span> <span class="dv">21</span>,</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">fill =</span> <span class="st">"purple"</span>, </span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">size =</span> <span class="dv">3</span>,</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">alpha =</span> .<span class="dv">7</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>  )<span class="sc">+</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>()<span class="sc">+</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Theoretical quantile"</span>,</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Sample quantile"</span>)<span class="sc">+</span></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProject_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="geom-density-plot" class="level2">
<h2 class="anchored" data-anchor-id="geom-density-plot">Geom Density Plot</h2>
<p>Here we look to ensure normality through the bell-shaped curve of the studentized resuals plotted</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pulliam_proj_mix_resid, <span class="fu">aes</span>(<span class="at">x=</span>.studresid))<span class="sc">+</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">"black"</span>,</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">fill =</span> <span class="st">"purple"</span>,</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">alpha =</span> .<span class="dv">7</span>)<span class="sc">+</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>,<span class="dv">0</span>,<span class="dv">3</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">3</span>,<span class="dv">3</span>))<span class="sc">+</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 5 rows containing non-finite outside the scale range
(`stat_density()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProject_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="model-means" class="level1">
<h1>Model Means</h1>
<p>Here we looking at model means bewteen individual treatments within a certain day</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>pulliam_proj_means_all <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(pulliam_proj_mod, <span class="sc">~</span>trt<span class="sc">|</span>day)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>pulliam_proj_means_all</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>day = 0:
 trt emmean   SE  df lower.CL upper.CL
 1    36.78 3.61 196   29.661     43.9
 2    38.91 3.61 196   31.788     46.0
 3    35.51 3.61 196   28.386     42.6
 4    39.11 3.61 196   31.984     46.2

day = 5:
 trt emmean   SE  df lower.CL upper.CL
 1    34.59 3.61 196   27.471     41.7
 2    51.68 3.61 196   44.560     58.8
 3    49.74 3.61 196   42.620     56.9
 4    63.37 3.61 196   56.251     70.5

day = 7:
 trt emmean   SE  df lower.CL upper.CL
 1    29.92 3.61 196   22.798     37.0
 2    24.01 3.61 196   16.887     31.1
 3    30.79 3.61 196   23.670     37.9
 4    47.10 3.61 196   39.980     54.2

day = 14:
 trt emmean   SE  df lower.CL upper.CL
 1    25.75 3.61 196   18.624     32.9
 2    37.20 3.61 196   30.079     44.3
 3    35.26 3.61 196   28.135     42.4
 4    50.48 3.61 196   43.354     57.6

day = 28:
 trt emmean   SE  df lower.CL upper.CL
 1    16.95 3.61 196    9.826     24.1
 2    34.46 3.61 196   27.335     41.6
 3    35.26 3.61 196   28.141     42.4
 4    57.37 3.61 196   50.247     64.5

day = 42:
 trt emmean   SE  df lower.CL upper.CL
 1    17.17 3.61 196   10.044     24.3
 2    19.08 3.61 196   11.956     26.2
 3    37.89 3.61 196   30.768     45.0
 4    63.27 3.61 196   56.146     70.4

day = 56:
 trt emmean   SE  df lower.CL upper.CL
 1     9.52 3.61 196    2.401     16.6
 2    10.87 3.61 196    3.750     18.0
 3     9.49 3.61 196    2.364     16.6
 4    30.16 3.61 196   23.034     37.3

day = 70:
 trt emmean   SE  df lower.CL upper.CL
 1     5.82 3.61 196   -1.299     12.9
 2     7.32 3.61 196    0.200     14.4
 3     7.49 3.61 196    0.364     14.6
 4    11.87 3.61 196    4.749     19.0

day = 93:
 trt emmean   SE  df lower.CL upper.CL
 1     6.55 3.61 196   -0.568     13.7
 2     7.92 3.61 196    0.793     15.0
 3     8.47 3.61 196    1.349     15.6
 4    13.73 3.61 196    6.604     20.8

day = 119:
 trt emmean   SE  df lower.CL upper.CL
 1     4.10 3.61 196   -3.023     11.2
 2     6.46 3.61 196   -0.659     13.6
 3     6.33 3.61 196   -0.788     13.5
 4     6.86 3.61 196   -0.262     14.0

day = 125:
 trt emmean   SE  df lower.CL upper.CL
 1     7.98 3.61 196    0.855     15.1
 2     8.56 3.61 196    1.441     15.7
 3     8.24 3.61 196    1.122     15.4
 4    15.43 3.61 196    8.308     22.6

day = 134:
 trt emmean   SE  df lower.CL upper.CL
 1     3.35 3.61 196   -3.776     10.5
 2     4.01 3.61 196   -3.110     11.1
 3     5.35 3.61 196   -1.777     12.5
 4     4.49 3.61 196   -2.634     11.6

day = 145:
 trt emmean   SE  df lower.CL upper.CL
 1    12.95 3.61 196    5.831     20.1
 2    17.73 3.61 196   10.605     24.9
 3    20.39 3.61 196   13.266     27.5
 4    17.42 3.61 196   10.292     24.5

day = 152:
 trt emmean   SE  df lower.CL upper.CL
 1    13.64 3.61 196    6.521     20.8
 2    26.59 3.61 196   19.472     33.7
 3    31.44 3.61 196   24.320     38.6
 4    22.81 3.61 196   15.687     29.9

day = 168:
 trt emmean   SE  df lower.CL upper.CL
 1    22.78 3.61 196   15.656     29.9
 2    29.28 3.61 196   22.156     36.4
 3    23.46 3.61 196   16.333     30.6
 4    22.03 3.61 196   14.909     29.2

day = 185:
 trt emmean   SE  df lower.CL upper.CL
 1     6.12 3.61 196   -1.006     13.2
 2     6.53 3.61 196   -0.591     13.7
 3     7.46 3.61 196    0.342     14.6
 4     8.71 3.61 196    1.584     15.8

day = 201:
 trt emmean   SE  df lower.CL upper.CL
 1     5.15 3.61 196   -1.970     12.3
 2     5.34 3.61 196   -1.779     12.5
 3     5.26 3.61 196   -1.861     12.4
 4     5.66 3.61 196   -1.459     12.8

day = 216:
 trt emmean   SE  df lower.CL upper.CL
 1     5.59 3.61 196   -1.532     12.7
 2     5.33 3.61 196   -1.794     12.5
 3     6.15 3.61 196   -0.977     13.3
 4     6.18 3.61 196   -0.944     13.3

day = 224:
 trt emmean   SE  df lower.CL upper.CL
 1     5.98 3.61 196   -1.147     13.1
 2     4.83 3.61 196   -2.294     12.0
 3     4.90 3.61 196   -2.227     12.0
 4     5.09 3.61 196   -2.029     12.2

Degrees-of-freedom method: kenward-roger 
Confidence level used: 0.95 </code></pre>
</div>
</div>
</section>
<section id="pairwise-comparisons" class="level1">
<h1>Pairwise comparisons</h1>
<p>Here we create our pairwise comparison and establish our letters of significance</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>pulliam_proj_cld_all <span class="ot">&lt;-</span> <span class="fu">cld</span>(pulliam_proj_means_all, </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>                   <span class="at">reversed=</span>T, </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">adjust=</span><span class="st">"none"</span>,</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">Letters=</span>letters)</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>pulliam_proj_cld_all</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>day = 0:
 trt emmean   SE  df lower.CL upper.CL .group
 4    39.11 3.61 196   31.984     46.2  a    
 2    38.91 3.61 196   31.788     46.0  a    
 1    36.78 3.61 196   29.661     43.9  a    
 3    35.51 3.61 196   28.386     42.6  a    

day = 5:
 trt emmean   SE  df lower.CL upper.CL .group
 4    63.37 3.61 196   56.251     70.5  a    
 2    51.68 3.61 196   44.560     58.8   b   
 3    49.74 3.61 196   42.620     56.9   b   
 1    34.59 3.61 196   27.471     41.7    c  

day = 7:
 trt emmean   SE  df lower.CL upper.CL .group
 4    47.10 3.61 196   39.980     54.2  a    
 3    30.79 3.61 196   23.670     37.9   b   
 1    29.92 3.61 196   22.798     37.0   b   
 2    24.01 3.61 196   16.887     31.1   b   

day = 14:
 trt emmean   SE  df lower.CL upper.CL .group
 4    50.48 3.61 196   43.354     57.6  a    
 2    37.20 3.61 196   30.079     44.3   b   
 3    35.26 3.61 196   28.135     42.4   bc  
 1    25.75 3.61 196   18.624     32.9    c  

day = 28:
 trt emmean   SE  df lower.CL upper.CL .group
 4    57.37 3.61 196   50.247     64.5  a    
 3    35.26 3.61 196   28.141     42.4   b   
 2    34.46 3.61 196   27.335     41.6   b   
 1    16.95 3.61 196    9.826     24.1    c  

day = 42:
 trt emmean   SE  df lower.CL upper.CL .group
 4    63.27 3.61 196   56.146     70.4  a    
 3    37.89 3.61 196   30.768     45.0   b   
 2    19.08 3.61 196   11.956     26.2    c  
 1    17.17 3.61 196   10.044     24.3    c  

day = 56:
 trt emmean   SE  df lower.CL upper.CL .group
 4    30.16 3.61 196   23.034     37.3  a    
 2    10.87 3.61 196    3.750     18.0   b   
 1     9.52 3.61 196    2.401     16.6   b   
 3     9.49 3.61 196    2.364     16.6   b   

day = 70:
 trt emmean   SE  df lower.CL upper.CL .group
 4    11.87 3.61 196    4.749     19.0  a    
 3     7.49 3.61 196    0.364     14.6  a    
 2     7.32 3.61 196    0.200     14.4  a    
 1     5.82 3.61 196   -1.299     12.9  a    

day = 93:
 trt emmean   SE  df lower.CL upper.CL .group
 4    13.73 3.61 196    6.604     20.8  a    
 3     8.47 3.61 196    1.349     15.6  a    
 2     7.92 3.61 196    0.793     15.0  a    
 1     6.55 3.61 196   -0.568     13.7  a    

day = 119:
 trt emmean   SE  df lower.CL upper.CL .group
 4     6.86 3.61 196   -0.262     14.0  a    
 2     6.46 3.61 196   -0.659     13.6  a    
 3     6.33 3.61 196   -0.788     13.5  a    
 1     4.10 3.61 196   -3.023     11.2  a    

day = 125:
 trt emmean   SE  df lower.CL upper.CL .group
 4    15.43 3.61 196    8.308     22.6  a    
 2     8.56 3.61 196    1.441     15.7  a    
 3     8.24 3.61 196    1.122     15.4  a    
 1     7.98 3.61 196    0.855     15.1  a    

day = 134:
 trt emmean   SE  df lower.CL upper.CL .group
 3     5.35 3.61 196   -1.777     12.5  a    
 4     4.49 3.61 196   -2.634     11.6  a    
 2     4.01 3.61 196   -3.110     11.1  a    
 1     3.35 3.61 196   -3.776     10.5  a    

day = 145:
 trt emmean   SE  df lower.CL upper.CL .group
 3    20.39 3.61 196   13.266     27.5  a    
 2    17.73 3.61 196   10.605     24.9  a    
 4    17.42 3.61 196   10.292     24.5  a    
 1    12.95 3.61 196    5.831     20.1  a    

day = 152:
 trt emmean   SE  df lower.CL upper.CL .group
 3    31.44 3.61 196   24.320     38.6  a    
 2    26.59 3.61 196   19.472     33.7  a    
 4    22.81 3.61 196   15.687     29.9  ab   
 1    13.64 3.61 196    6.521     20.8   b   

day = 168:
 trt emmean   SE  df lower.CL upper.CL .group
 2    29.28 3.61 196   22.156     36.4  a    
 3    23.46 3.61 196   16.333     30.6  a    
 1    22.78 3.61 196   15.656     29.9  a    
 4    22.03 3.61 196   14.909     29.2  a    

day = 185:
 trt emmean   SE  df lower.CL upper.CL .group
 4     8.71 3.61 196    1.584     15.8  a    
 3     7.46 3.61 196    0.342     14.6  a    
 2     6.53 3.61 196   -0.591     13.7  a    
 1     6.12 3.61 196   -1.006     13.2  a    

day = 201:
 trt emmean   SE  df lower.CL upper.CL .group
 4     5.66 3.61 196   -1.459     12.8  a    
 2     5.34 3.61 196   -1.779     12.5  a    
 3     5.26 3.61 196   -1.861     12.4  a    
 1     5.15 3.61 196   -1.970     12.3  a    

day = 216:
 trt emmean   SE  df lower.CL upper.CL .group
 4     6.18 3.61 196   -0.944     13.3  a    
 3     6.15 3.61 196   -0.977     13.3  a    
 1     5.59 3.61 196   -1.532     12.7  a    
 2     5.33 3.61 196   -1.794     12.5  a    

day = 224:
 trt emmean   SE  df lower.CL upper.CL .group
 1     5.98 3.61 196   -1.147     13.1  a    
 4     5.09 3.61 196   -2.029     12.2  a    
 3     4.90 3.61 196   -2.227     12.0  a    
 2     4.83 3.61 196   -2.294     12.0  a    

Degrees-of-freedom method: kenward-roger 
Confidence level used: 0.95 
significance level used: alpha = 0.05 
NOTE: If two or more means share the same grouping symbol,
      then we cannot show them to be different.
      But we also did not show them to be the same. </code></pre>
</div>
</div>
<section id="light-wrangling" class="level2">
<h2 class="anchored" data-anchor-id="light-wrangling">Light Wrangling</h2>
<p>Here we are doing some light wrangling before moving on to our final plotting, but only needed if we decide to present the data in a way displaying “trt + day” together</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>pulliam_proj_cld_selected <span class="ot">&lt;-</span> pulliam_proj_cld_all <span class="sc">%&gt;%</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">letter=</span><span class="fu">trimws</span>(.group)) <span class="sc">%&gt;%</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">trtname =</span> <span class="fu">paste0</span>(trt,<span class="st">"+"</span>, day))</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>pulliam_proj_cld_selected</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   trt day  emmean      SE       df   lower.CL upper.CL .group letter trtname
3    4   0 39.1070 3.61172 195.6823 31.9841066 46.22989      a      a     4+0
1    2   0 38.9104 3.61172 195.6823 31.7875066 46.03329      a      a     2+0
2    1   0 36.7838 3.61172 195.6823 29.6609066 43.90669      a      a     1+0
4    3   0 35.5086 3.61172 195.6823 28.3857066 42.63149      a      a     3+0
5    4   5 63.3734 3.61172 195.6823 56.2505066 70.49629    a        a     4+5
7    2   5 51.6824 3.61172 195.6823 44.5595066 58.80529     b       b     2+5
6    3   5 49.7424 3.61172 195.6823 42.6195066 56.86529     b       b     3+5
8    1   5 34.5936 3.61172 195.6823 27.4707066 41.71649      c      c     1+5
10   4   7 47.1024 3.61172 195.6823 39.9795066 54.22529     a       a     4+7
9    3   7 30.7928 3.61172 195.6823 23.6699066 37.91569      b      b     3+7
11   1   7 29.9204 3.61172 195.6823 22.7975066 37.04329      b      b     1+7
12   2   7 24.0096 3.61172 195.6823 16.8867066 31.13249      b      b     2+7
13   4  14 50.4764 3.61172 195.6823 43.3535066 57.59929    a        a    4+14
15   2  14 37.2014 3.61172 195.6823 30.0785066 44.32429     b       b    2+14
14   3  14 35.2580 3.61172 195.6823 28.1351066 42.38089     bc     bc    3+14
16   1  14 25.7468 3.61172 195.6823 18.6239066 32.86969      c      c    1+14
17   4  28 57.3696 3.61172 195.6823 50.2467066 64.49249    a        a    4+28
18   3  28 35.2634 3.61172 195.6823 28.1405066 42.38629     b       b    3+28
19   2  28 34.4582 3.61172 195.6823 27.3353066 41.58109     b       b    2+28
20   1  28 16.9492 3.61172 195.6823  9.8263066 24.07209      c      c    1+28
21   4  42 63.2686 3.61172 195.6823 56.1457066 70.39149    a        a    4+42
22   3  42 37.8908 3.61172 195.6823 30.7679066 45.01369     b       b    3+42
23   2  42 19.0788 3.61172 195.6823 11.9559066 26.20169      c      c    2+42
24   1  42 17.1668 3.61172 195.6823 10.0439066 24.28969      c      c    1+42
27   4  56 30.1566 3.61172 195.6823 23.0337066 37.27949     a       a    4+56
25   2  56 10.8724 3.61172 195.6823  3.7495066 17.99529      b      b    2+56
26   1  56  9.5238 3.61172 195.6823  2.4009066 16.64669      b      b    1+56
28   3  56  9.4870 3.61172 195.6823  2.3641066 16.60989      b      b    3+56
29   4  70 11.8716 3.61172 195.6823  4.7487066 18.99449      a      a    4+70
30   3  70  7.4866 3.61172 195.6823  0.3637066 14.60949      a      a    3+70
31   2  70  7.3232 3.61172 195.6823  0.2003066 14.44609      a      a    2+70
32   1  70  5.8234 3.61172 195.6823 -1.2994934 12.94629      a      a    1+70
33   4  93 13.7268 3.61172 195.6823  6.6039066 20.84969      a      a    4+93
34   3  93  8.4714 3.61172 195.6823  1.3485066 15.59429      a      a    3+93
35   2  93  7.9156 3.61172 195.6823  0.7927066 15.03849      a      a    2+93
36   1  93  6.5544 3.61172 195.6823 -0.5684934 13.67729      a      a    1+93
37   4 119  6.8608 3.61172 195.6823 -0.2620934 13.98369      a      a   4+119
39   2 119  6.4634 3.61172 195.6823 -0.6594934 13.58629      a      a   2+119
38   3 119  6.3346 3.61172 195.6823 -0.7882934 13.45749      a      a   3+119
40   1 119  4.0996 3.61172 195.6823 -3.0232934 11.22249      a      a   1+119
41   4 125 15.4306 3.61172 195.6823  8.3077066 22.55349      a      a   4+125
43   2 125  8.5636 3.61172 195.6823  1.4407066 15.68649      a      a   2+125
42   3 125  8.2448 3.61172 195.6823  1.1219066 15.36769      a      a   3+125
44   1 125  7.9774 3.61172 195.6823  0.8545066 15.10029      a      a   1+125
45   3 134  5.3460 3.61172 195.6823 -1.7768934 12.46889      a      a   3+134
46   4 134  4.4892 3.61172 195.6823 -2.6336934 11.61209      a      a   4+134
48   2 134  4.0128 3.61172 195.6823 -3.1100934 11.13569      a      a   2+134
47   1 134  3.3466 3.61172 195.6823 -3.7762934 10.46949      a      a   1+134
49   3 145 20.3890 3.61172 195.6823 13.2661066 27.51189      a      a   3+145
52   2 145 17.7282 3.61172 195.6823 10.6053066 24.85109      a      a   2+145
50   4 145 17.4152 3.61172 195.6823 10.2923066 24.53809      a      a   4+145
51   1 145 12.9538 3.61172 195.6823  5.8309066 20.07669      a      a   1+145
53   3 152 31.4428 3.61172 195.6823 24.3199066 38.56569     a       a   3+152
56   2 152 26.5946 3.61172 195.6823 19.4717066 33.71749     a       a   2+152
54   4 152 22.8094 3.61172 195.6823 15.6865066 29.93229     ab     ab   4+152
55   1 152 13.6438 3.61172 195.6823  6.5209066 20.76669      b      b   1+152
60   2 168 29.2788 3.61172 195.6823 22.1559066 36.40169      a      a   2+168
57   3 168 23.4562 3.61172 195.6823 16.3333066 30.57909      a      a   3+168
59   1 168 22.7792 3.61172 195.6823 15.6563066 29.90209      a      a   1+168
58   4 168 22.0314 3.61172 195.6823 14.9085066 29.15429      a      a   4+168
61   4 185  8.7070 3.61172 195.6823  1.5841066 15.82989      a      a   4+185
62   3 185  7.4646 3.61172 195.6823  0.3417066 14.58749      a      a   3+185
63   2 185  6.5320 3.61172 195.6823 -0.5908934 13.65489      a      a   2+185
64   1 185  6.1172 3.61172 195.6823 -1.0056934 13.24009      a      a   1+185
65   4 201  5.6640 3.61172 195.6823 -1.4588934 12.78689      a      a   4+201
67   2 201  5.3440 3.61172 195.6823 -1.7788934 12.46689      a      a   2+201
66   3 201  5.2618 3.61172 195.6823 -1.8610934 12.38469      a      a   3+201
68   1 201  5.1524 3.61172 195.6823 -1.9704934 12.27529      a      a   1+201
70   4 216  6.1786 3.61172 195.6823 -0.9442934 13.30149      a      a   4+216
69   3 216  6.1460 3.61172 195.6823 -0.9768934 13.26889      a      a   3+216
71   1 216  5.5904 3.61172 195.6823 -1.5324934 12.71329      a      a   1+216
72   2 216  5.3286 3.61172 195.6823 -1.7942934 12.45149      a      a   2+216
74   1 224  5.9762 3.61172 195.6823 -1.1466934 13.09909      a      a   1+224
75   4 224  5.0938 3.61172 195.6823 -2.0290934 12.21669      a      a   4+224
76   3 224  4.8958 3.61172 195.6823 -2.2270934 12.01869      a      a   3+224
73   2 224  4.8290 3.61172 195.6823 -2.2938934 11.95189      a      a   2+224</code></pre>
</div>
</div>
</section>
</section>
<section id="final-plot" class="level1">
<h1>Final Plot</h1>
<p>Here we bring in our initial wrangled data to create boxplots with error bars, we set our dependent variable of mg_kg_tin to the y axis and our independent variables of day and treatment to the y axis, displaying both through the use of the facet_grid function. Our letters our created trough our emmean values we created a few steps above, then we save it in a size that makes it legible.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>pulliam_proj_w1 <span class="ot">&lt;-</span> pulliam_proj_w <span class="sc">%&gt;%</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(<span class="at">trtname =</span> <span class="fu">paste0</span>(trt,<span class="st">"+"</span>, day))</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">fill =</span> trtname))<span class="sc">+</span></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Raw data and boxplots  </span></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">data =</span> pulliam_proj_w1,</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>               <span class="fu">aes</span>(<span class="at">x =</span> trt, <span class="at">y =</span> mg_kg_tin),</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>               <span class="at">alpha =</span> .<span class="dv">8</span>) <span class="sc">+</span></span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">data =</span> pulliam_proj_w1,</span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>               <span class="fu">aes</span>(<span class="at">x =</span> trt, <span class="at">y =</span> mg_kg_tin),</span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a>              <span class="at">shape =</span> <span class="dv">21</span>,</span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a>              <span class="at">size =</span> <span class="dv">3</span>,</span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a>              <span class="at">alpha =</span> .<span class="dv">6</span>) <span class="sc">+</span></span>
<span id="cb48-15"><a href="#cb48-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Adding letters and titles</span></span>
<span id="cb48-16"><a href="#cb48-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_label</span>(<span class="at">data =</span> pulliam_proj_cld_selected,</span>
<span id="cb48-17"><a href="#cb48-17" aria-hidden="true" tabindex="-1"></a>            <span class="fu">aes</span>(<span class="at">x =</span> trt, <span class="at">y =</span> emmean, <span class="at">label =</span> letter),</span>
<span id="cb48-18"><a href="#cb48-18" aria-hidden="true" tabindex="-1"></a>            <span class="at">fill =</span> <span class="st">"white"</span>) <span class="sc">+</span></span>
<span id="cb48-19"><a href="#cb48-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Treatments Grouped By Day"</span>,</span>
<span id="cb48-20"><a href="#cb48-20" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Mg/Kg of Total Inorganic Nitrogen"</span>) <span class="sc">+</span></span>
<span id="cb48-21"><a href="#cb48-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>() <span class="sc">+</span></span>
<span id="cb48-22"><a href="#cb48-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.grid.major.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb48-23"><a href="#cb48-23" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.grid.minor.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb48-24"><a href="#cb48-24" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position =</span> <span class="st">"none"</span>) <span class="sc">+</span></span>
<span id="cb48-25"><a href="#cb48-25" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb48-26"><a href="#cb48-26" aria-hidden="true" tabindex="-1"></a><span class="fu">facet_grid</span>(<span class="sc">~</span> day)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="FinalProject_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="2880"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggsave</span>(<span class="st">"../output/pulliam_project_final_plot.png"</span>,</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">width =</span> <span class="dv">30</span>,</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>       <span class="at">height =</span> <span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<p>Our graph shows no significance in soil total inorganic nitrogen on day 0 before poultry litter application. After day 0, there are significant differences in soil inorganic nitrogen from days 5-56 which makes sense. It is typical for poultry litter and other organic fertilizers to take a few weeks/month for microbes to bring their organic compounds into inorganic plant available forms which is what we are seeing in days 5 through 56. The lack of significant results from days 70-145 could be expected as cover crops are uptaking the inorganic nitrogen. On days 152 and days 185 there is a peak in soil inorganic nitrogen which is likely due to the mineralization of the incorporated cover crop in addition to the small pre-plant application of an organic fertilizer to supply the cash crop (kale) with enough N for the season. After this peak, there is another period of time with stable and non-significant soil inorganic nitrogen from days 185 to 224 which is likely due to the kale uptake of inorganic nitrogen. While treatment 4 (highest application of poultry litter) has the highest soil inorganic nitrogen as expected, we still need to analyze and visualize other nutrients/variables to examine the effects of this level of poultry litter applications.</p>
<p>The process and visualization of this data allows us to see how different rates of poultry litter provide different amounts of soil inorganic nitrogen at different times. Being able to visualize this allows for researcher and organic growers to make more informed applications of organic fertilizers to optimize and synchronize soil nutrients with plant uptake. Synchronization is a complex problem for organic growers as all organic fertilizers will mineralize and release their nutrients different depending on environmental and soil conditions. Being able to visualize this process can help minimize nutrient losses and increase fertilizer efficacy/yields. Further analysis will be conducted to see if poultry application to cover crops is suitable option for organic growers to avoid food pathogen risk while using low-cost fertilizers such as poultry litter.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>